[workspace]
members = [
    "socket_bin",
    "socket_bin_async",
    "socket_lib",
    "socket_lib_async",
    "thermo_bin",
    "thermo_bin_async",
    "thermo_lib",
    "thermo_lib_async",
]

resolver = "2"